name: Generate GitHub Metrics
on:
  schedule:
    - cron: "0 0 * * *" # Updates daily at midnight
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Isometric Commit Calendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

      - name: Notable Contributions (Indepth)
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.notable.indepth.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_notable: yes
          plugin_notable_indepth: yes
          plugin_notable_repositories: yes

      - name: LeetCode Stats
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.leetcode.svg
          token: NOT_NEEDED
          base: ""
          plugin_leetcode: yes
          plugin_leetcode_user: khantdotcom
          plugin_leetcode_sections: solved, skills, recent
